# -*- coding: utf-8 -*-
"""19th August 2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12C1T8dF26EiL4jAlFPDnscx2g8RQUXIE

1.Declare two variables, `x` and `y`, and assign them integer values. Swap thevalues of these variables without using any temporary variable.
"""

x=52
y=25
print("Before Swapping:",x,y)
x,y=y,x
print("After Swapping: ",x,y)

"""2. Create a program that calculates the area of a rectangle. Take the length and
width as inputs from the user and store them in variables. Calculate and
display the area.
"""

length=int(input("Enter length of rectangle: "))
width=int(input("Enter width of rectangle: "))
print("Area of rectangle is: ",length*width)

"""3. Write a Python program that converts temperatures from Celsius to
Fahrenheit. Take the temperature in Celsius as input, store it in a variable,
convert it to Fahrenheit, and display the result.
"""

Celsius=int(input("Enter temperature in Celsius: "))
print("Temperature in Fahrenheit is: ",Celsius*1.8+32)

"""1. Write a Python program that takes a string as input and prints the length of
the string.
"""

string=input("Enter String: ")
print("Length of the given string: ",len(string))

"""2. Create a program that takes a sentence from the user and counts the number
of vowels (a, e, i, o, u) in the string.
"""

string=input("Enter String: ")
string=string.replace(" ",'')
count=0
vowels='aeiouAEIOU'
for i in string:
   if i in vowels:
    count +=1

print(count)

"""3. Given a string, reverse the order of characters using string slicing and print
the reversed string.
"""

string=input("Enter String: ")
print("Reversed String: ",string[::-1])

"""4. Write a program that takes a string as input and checks if it is a palindrome
(reads the same forwards and backwards).
"""

string=input("Enter String: ")
rev=string[::-1]
if string == rev:
  print(f"{string} String is palindrome")
else:
  print(f"{string} String is not palindrome")

"""5. Create a program that takes a string as input and removes all the spaces from
it. Print the modified string without spaces.
"""

string=input("Enter String: ")
string=string.replace(" ",'')
print("String without empty spaces: ",string)